.github/workflows/main.yml, build.sh
- github action 오류
- 이번 push에도 오류가 나면 앞으로 act 라이브러리를 도입해서 도커를 통해 로컬에서 테스트후 pr 올리겠습니다
연관된 issue: #patch
=> fix: github action 오류 yaml 파일 수정

src/domains/Login/components/LocationMove.tsx, src/pages/Setting.tsx, src/shared/ui/layout/BottomNavigationLayout.tsx, src/shared/ui/layout/Flex.tsx, tailwind.config.js
- Flex 컴포넌트에 gap 속성 적용 안되는 에러 해결
-
=> Fix: home gap ui 에러 해결

src/pages/Login.tsx
- login 컴포넌트에서 Flex 컴포넌트를 사용하여 구조 개선 및 코드 정리
-
=> fix: login 컴포넌트 에러 정리

src/pages/Login.tsx
=> feat: login 페이지에 YoutubeIcon 추가

src/domains/Home/components/HasTokenChannelInfo.tsx
…lProfile 훅을 사용하여 데이터 동적 처리
-
-
=> fix: channelCard api 연결

src/domains/GrowthPrediction/components/GrowthPredictionFunnel.tsx, src/domains/GrowthPrediction/hooks/useGrowthPredictionQuery.ts, src/domains/GrowthPrediction/model/type.ts, src/domains/GrowthPrediction/service/handler.ts, src/domains/GrowthPrediction/service/queryOption.ts, src/domains/Popular/hooks/usePopularQuery.ts, src/domains/Popular/model/type.ts, src/domains/Popular/service/handler.ts, src/domains/Popular/service/queryOption.ts, src/domains/Strategy/hooks/useStrategy.ts, src/domains/Strategy/model/type.ts, src/domains/Strategy/service/handler.ts, src/domains/StrengthWeakness/components/ProgressBar.tsx, src/domains/StrengthWeakness/components/StrengthWeaknessFunnel.tsx, src/domains/StrengthWeakness/hooks/useStrengthWeakStatsQuery.ts, src/domains/StrengthWeakness/model/type.ts, src/domains/StrengthWeakness/service/handler.ts, src/domains/StrengthWeakness/service/queryOption.ts, src/pages/GrowthPrediction.tsx, src/pages/StrengthWeakness.tsx
- 스크린샷 api 제외하고 커스텀 훅으로 api 로직 다 작성
-
연관된 issue: #prediction
=> Feat: api 커스텀 훅 제작

src/domains/Home/hooks/useChannelOption.ts
=> feat: 채널 옵션을 저장하는 훅 추가

src/domains/Analysis/components/AnalysisState.tsx, src/domains/Analysis/components/DataFetchComponents.tsx, src/domains/Analysis/components/ProcessStateItem.tsx, src/pages/Analysis.tsx
- close #58 
- 조회수 top 3 api연결
- 채널 정보 api연결
- 성장예측 api연결
- 강약점 분석 api연결
https://github.com/user-attachments/assets/402c7934-1289-462e-aa38-687aac29c560
-
연관된 issue: #api
=> Feat: 분석중 api 연결

src/domains/Analysis/components/DataFetchComponents.tsx
=> feat: analys 완료 후 페이지 네비게이팅 구현

src/domains/Strategy/hooks/useStrategy.ts, src/domains/Strategy/service/handler.ts, src/pages/Strategy.tsx
- 배포후 api 관련 에러 추적을 위한 수정
-
연관된 issue: #strategy
=> feat: 에러 추적

src/domains/Strategy/hooks/useStrategy.ts, src/domains/Strategy/model/type.ts, src/domains/Strategy/service/handler.ts, src/pages/Strategy.tsx, src/pages/StrategyBefore.tsx
- post youtube/pinecone/strategy 수정
- get youtube/pinecone/strategy 수정
-
연관된 issue: #strategy
=> fix: api 오류 수정

src/app/api/httpClient.ts, src/app/api/type.ts, src/app/provider/QuerySuspenseBoundary.tsx, src/domains/Home/components/HasTokenChannelInfo.tsx, src/domains/Login/hooks/useAuthToken.ts, src/domains/Login/model/type.ts, src/domains/Login/service/handler.ts, src/mocks/handler/auth.ts, src/mocks/handler/channel.ts, src/pages/Detail.tsx, src/pages/UserInfo.tsx
- access_token 만료시 작업했습니다
- resfresh 로직 추가했습니다.
-
=> Fix: refresh token 로직 추가

src/domains/Detail/components/FrequentlyAskedQuestions.tsx, src/domains/Detail/components/Recommendation.tsx, src/pages/Home.tsx, src/pages/Setting.tsx, src/pages/Strategy.tsx
- 이미지 저장알림 추가
- FAQ 아코디언 안닫힘 버그 수정
- FAQ ui 수정
- 외부 링크 ui 오류 수정 
-
=> feat: 이미지 저장 알림 추가

src/domains/GrowthPrediction/components/VideoPlayer.tsx
=> fix: 비디오 파일 경로 수정

src/domains/GrowthPrediction/components/VideoPlayer.tsx
=> Fix: video 외부 링크로 변환

package-lock.json, package.json, src/app/api/httpClient.ts, src/app/api/type.ts, src/domains/GrowthPrediction/components/VideoPlayer.tsx, src/shared/lib/storage.ts
- ios 애니메이션 표시
- localStorage -> session 스토리지로 변경
-
=> Fix: ios 애니메이션 적용 및 session 스토리지로 변경

src/domains/GrowthPrediction/components/VideoPlayer.tsx, src/pages/Detail.tsx
=> Fix: session스토리지 변환 및 웹 mp4 문제 해결

src/domains/GrowthPrediction/components/DelayText.tsx, src/domains/UserInformation/components/SheetContent.tsx, src/pages/Home.tsx, src/pages/OnBoarding.tsx, src/pages/Popular.tsx, src/shared/components/Buttons/index.tsx
- onboarding 페이지 local storage에서 sessionstorage로 변경
- user info 페이지 확인버튼 비활성화
- 인기 top3 에러 메세지 가운데 맞춤
- mp4 페이지 다음 버튼 가운데 맞춤
=> fix: ui 전반적인 수정

src/domains/Popular/components/PopularCard/index.tsx, src/domains/onBoarding/components/OnBoardingFrame.tsx, src/pages/Strategy.tsx, src/shared/components/BottomSheetModal/items/CustomHeader.tsx, src/shared/components/Buttons/index.tsx, src/shared/components/Chips/index.tsx
=> fix: 글자 크기 및 fontweight 수정

src/domains/GrowthPrediction/components/MovingBlurCard.tsx, src/domains/StrengthWeakness/components/Graph.tsx, src/domains/StrengthWeakness/lib/strengthWeaknessTrasnform.ts, src/shared/ui/components/Text.tsx
- 강약점 카드 max-width 해제
- 성장예측 카드 자리수에 따라 폰트 크기 조절
-
=> Fix: 자리수에 대한 폰트 크기 조절 

src/domains/Home/components/ChannelCommonCard.tsx, src/domains/Home/components/HasTokenChannelInfo.tsx, src/domains/StrengthWeakness/components/step/WeaknessStep.tsx, src/pages/UserInfo.tsx, src/shared/ui/components/Card.tsx
- card medium 속성 추가
- 강약점 card 약점 max-w 삭제
-
=> Fix: card 컴포넌트 속성 추가 및 강약점 card

src/pages/UserInfo.tsx
=> fix: userInfo 컴포넌트에서 텍스트 크기 및 버튼 패딩 조정

src/domains/Detail/components/TopPage.tsx, src/domains/onBoarding/hooks/useDotButton.tsx, src/pages/OnBoarding.tsx, src/shared/components/Carousel/index.tsx
- 캐러셀 점들 추가 (터치로 이동가능)
- 캐러셀 방식 변경
연관된 issue: #dots
=> feat: Carousel dots 추가

src/domains/Analysis/components/DataFetchComponents.tsx, src/domains/Home/components/ChannelCommonCard.tsx, src/mocks/handler/channel.ts, src/pages/Analysis.tsx
=> Fix: WMA api 요청 순서 변경

src/domains/Setting/components/SettingToast.tsx, src/pages/Setting.tsx
=> feat: Logout 구현

src/domains/Strategy/components/SplitString.tsx, src/pages/Strategy.tsx
- splitstrategy 페이지 예외처리
- strategy bold 수정
=> fix: strategy 페이지 예외처리 및 bold 수정

src/pages/Strategy.tsx
=> fix: strategy 접히기 글자수 수정

src/domains/Setting/components/SettingToast.tsx, src/mocks/handler/channel.ts, src/pages/Setting.tsx
=> Fix: 계정 삭제 문구 변경 및 설정 페이지 노션페이지로 변경

src/domains/Login/model/type.ts, src/domains/Login/service/handler.ts, src/pages/Oauth.tsx, src/pages/OauthMeta.tsx
- meta token 받는 api 연결 오류 해결
연관된 issue: #instagram
=> Fix: callback api 오류 해결

src/domains/Strategy/model/type.ts, src/pages/StrategyB.tsx
=> Fix: 비법페이지 안넘어가는 에러

.github/workflows/main.yml
- github action 수정
연관된 issue: #error
=> fix: fixing main.yml

.github/workflows/main.yml
Reverts Central-MakeUs/Spark-Front#109
연관된 issue: #109
=> Revert "fix: modify main.yml"

.github/workflows/main.yml
-  push 되면 forked 된 repo로  push  자동화 action 적용
연관된 issue: #to
=> fix: main.yml 수정

.github/workflows/main.yml
- check out 에 PAT 추가
연관된 issue: #out
=> fix: add PAT to checkout

src/domains/Strategy/components/ActionButtonsRow.tsx, src/pages/Home.tsx, src/pages/Setting.tsx, src/shared/util/handleOpenNewTab.ts
Reverts Central-MakeUs/Spark-Front#118
연관된 issue: #118
=> Revert "Revert "Feat: Strategy linking""
